import type { Metadata } from "next";
import { sfPro } from "./fonts";
import "./globals.scss";
import { Navbar } from "./components";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${sfPro.className} antialiased tracking-wide bg-dark`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
